#!/bin/bash 
#~/cell is mount point for usb  and android 
if [ "$(ls -A ~/cell)" ]; then
    [ "$(printf "No\\nYes" | dmenu -i -p "Really Umount cell?")" = "Yes" ] && sh /home/omar/scripts/dmenuumount
    #sh /home/omar/scripts/dmenuumount
else 
    [ "$(printf "No\\nYes" | dmenu -i -p "Really Mount cell?")" = "Yes" ] && sh /home/omar/scripts/dmenumount
    #sh /home/omar/scripts/dmenumount
fi 

