#!/bin/bash
OPT=$(echo -e "Mount\nUmount" | dmenu -nb '#191919' -nf '#fea63c' -sb '#fea63c' -sf '#191919' -fn 'NotoMonoRegular:bold:pixelsize=16' -p "Choose action: ")
case $OPT in
	Mount ) ~/scripts/dmenumount ;; 
	Umount ) ~/scripts/dmenuumount ;;
	*) ;;
esac

