#!/bin/bash
#sxiv via dmenu is opened only if directory existing 
while true; do
    open=$(ls --group-directories-first --file-type | dmenu "$@")
    if [[ -d "$open" ]]; then
        cd "$open"
    else
        if [[ "$open" != "" ]]; then
            cd $open
            sxiv *
        fi
        exit 0
    fi
done
