#!/bin/bash 
cd ~/.config/
cp -r alacritty fish mpd neofetch ranger sxhkd zathura arco-dwm htop mpv paru starship.toml vlc dmscripts/config i3 ncmpcpp pcmanfm styli.sh yay /home/omar/Documents/Github/dotfiles/config
cp -r /home/omar/scripts/* /home/omar/Documents/Github/dotfiles/scripts 

