#!/bin/bash 
doas pacman -S neovim 
doas pacman -S mpv 
doas pacman -S mpd 
doas pacman -S nnn 
doas pacman -S dolphin 
doas pacman -S pcmanfm 
doas pacman -S alacritty 
doas pacman -S fish 
doas pacman -S sxhkd 
doas pacman -S dmenu 
doas pacman -S python-pywal 
doas pacman -S qt5ct 
doas pacman -S firefox 
doas pacman -S google-chrome 
doas pacman -S brave-bin 
doas pacman -S qutebrowser 
doas pacman -S gufw 
doas pacman -S moc 
doas pacman -S ncmpcpp 
doas pacman -S kvantum 
doas pacman -S sxiv 
doas pacman -S zathura 
doas pacman -S clipmenu 
doas pacman -S youtube-dl 
doas pacman -S ffmpeg 
doas pacman -S kdialog 
doas pacman -S nvidia 
doas pacman -S nvidia-lts 
doas pacman -S exa 
doas pacman -S cmatrix 
doas pacman -S droidcam 
doas pacman -S pulseaudio 
doas pacman -S pulsemixer 
doas pacman -S trash-cli 
doas pacman -S okular 
doas pacman -S htop 
doas pacman -S nvtop 
doas pacman -S paru 
doas pacman -S lxappearance 
doas pacman -S xdotool 
