#!/bin/bash
neofetch 
cd ~/ffmpeg 
echo "---------------------------------------------"
echo "✘ ❯❯ $(pwd)"
echo "---------------------------------------------"
read -p '❯❯❯ Enter name of file : ' name 
echo "---------------------------------------------"
youtube-dl --extract-audio --audio-format mp3 $(xclip -o) -o $name.mp3



