#!/bin/bash
mkdir -p output
for i in *.mp4 *.mkv; do
  printf "save as output/${i%%.*}.mp3"
  ffmpeg -i "$i" "output/${i%%.*}.mp3"  
done

cd ~/ffmpeg/output
for i in *.mp3; do 
  echo ------------------------
  echo "✘ ❯❯ $i"
  read -p "Enter name of source ✘ ❯❯ " name
  mv "$i" $name.mp3
done

