#!/bin/bash
#OPT=$(echo -e "lock\nlogout\nreboot\nsuspend\nhibernate\nshutdown" | dmenu -i -p "Choose action: ")
OPT=$(echo -e "lock\nlogout\nreboot\nsuspend\nhibernate\nshutdown" | dmenu -nb '#191919' -nf '#fea63c' -sb '#fea63c' -sf '#191919' -fn 'NotoMonoRegular:bold:pixelsize=16' -p "Choose action: ")
case $OPT in
	lock ) betterlockscreen -l dimblur -- --time-str="%H:%M" ;;
	logout ) xdotool key "super+shift+q" ;; 
	reboot) reboot     ;;
	suspend) systemctl suspend   ;;
	hibernate ) systemctl hibernate ;;
	shutdown) shutdown now ;;
	*) ;;
esac

