#!/bin/sh 

PIDFILE="/tmp/record.pid"

if [ -s $PIDFILE ]
then
	kill $(cat $PIDFILE)
	rm -rf $PIDFILE
else
	#ffmpeg -video_size 1920x1080 -framerate 30 -f x11grab -i :0 -f alsa -i hw:0 -af "volume=10" ~/ffmpeg/screencast/$(date +%s).mp4 & echo $! > $PIDFILE
  ffmpeg -framerate 30 -video_size 1920x1080 -f x11grab -i :0 -f pulse -i default -vcodec libx264  -preset fast -acodec pcm_s16le ~/ffmpeg/screencast/$(date +%s).mp4 & echo $! > $PIDFILE


fi
